name: MLFlow CI Workflow

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Copy Project Files
        run: |
          mkdir my_mlflow_project  # Create a target directory
          shopt -s dotglob  # Include hidden files (starting with dot)
          cp -r $GITHUB_WORKSPACE/* my_mlflow_project/
          shopt -u dotglob  # Disable dotglob to avoid copying '.' and '..'
          cd my_mlflow_project/

      - name: Run Tests
        run: |
          python code/tests.py
